package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: 0
  {% if GIT_DESCRIBE_NUMBER|int > 0 %}
  string: py{{ PY_VER }}_git_{{ GIT_BUILD_STR }}
  {% endif %}
  preserve_egg_dir: True

requirements:
  build:
    - python
  run:
    - python
    - conda  >=4.1
    - jinja2
    - patchelf      [linux]

test:
  # more tests in run_test.py (runs the tests folder)
  requires:
    - pytest
    - pytest-cov
    - pytest-env
    - mock
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD 3-clause
