package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: py{{ PY_VER }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - python
  run:
    - python
    - conda
    - jinja2
    - patchelf      [linux]

test:
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
